POST http://localhost:3000/login/
Content-Type : application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}


###

GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAzMzQ1ODQyfQ.TVpVX-GO7z-v1faA49QxZF7Ssh1qAt2gkr14--7pqlM

###
GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAzMzQ1ODQyfQ.TVpVX-GO7z-v1faA49QxZF7Ssh1qAt2gkr14--7pqlM

###
POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAzMzQ1ODQyfQ.TVpVX-GO7z-v1faA49QxZF7Ssh1qAt2gkr14--7pqlM

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}


###

GET http://localhost:3000/districts/320/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAzMzQ1ODQyfQ.TVpVX-GO7z-v1faA49QxZF7Ssh1qAt2gkr14--7pqlM

###

DELETE http://localhost:3000/districts/322/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAzMzQ1ODQyfQ.TVpVX-GO7z-v1faA49QxZF7Ssh1qAt2gkr14--7pqlM


###
PUT http://localhost:3000/districts/320/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAzMzQ1ODQyfQ.TVpVX-GO7z-v1faA49QxZF7Ssh1qAt2gkr14--7pqlM

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
